# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4607a5bd9cbd571c13264efae78e4e10f5a5df295d02db9f67be75894cdd21340a76fd8ce3df41c51747519d2f1c2905aee67214bf0b28f664b037df1c9e390a
test:
  secret_key_base: b06732cf009aec33388387c0683c87f2fb4f7f7ac97d0e5622b4361c33ff9f12f72c377a57cb3eb05819a401995f6a34211cca1c5b123729ae4f056bf72d8339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
